---
- hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - { role: bootstrap }
    - { role: docker }
    - { role: kubeadm }

- hosts: k8s_master
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - include_role:
        name: load-balancer
      when: groups.k8s_master | length > 1

- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - import_role:
        name: kubeadm
        tasks_from: init.yml

- hosts: all
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - import_role:
        name: kubeadm
        tasks_from: join.yml

- hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - { role: cni/calico }
    - { role: helm }