---
- debug:
    msg: "{{ kubeadm_init_command }}"

# 初始化 kubernetes 控制平面节点
- name: kubeadm init
  command: "{{ kubeadm_init_command }}"
  notify:
    - Set up kubectl

# 获取 kubeadm join 命令
- name: Get kubeadm join command
  command: "kubeadm token create --print-join-command"
  register: join_command_raw

# 将 node 节点 kubeadm join 命令加入 fact
- set_fact:
    node_join_command: "{{ join_command_raw.stdout_lines[0] }}"

- debug:
    msg: "{{ join_command_raw.stdout_lines[0] }}"

- meta: flush_handlers