---
- debug:
    msg: "{{ kubeadm_init_command }}"

# 初始化 kubernetes 控制平面节点
- name: kubeadm init
  command: "{{ kubeadm_init_command }}"
  notify:
    - Set up kubectl

# 获取 kubeadm join 命令
- name: Get kubeadm join command
  command: "kubeadm token create --print-join-command"
  register: join_command_raw

# 获取 control plane join certificate key
- name: Get control plane join certificate key
  command: "kubeadm init phase upload-certs --upload-certs"
  register: certificate_key_raw
  when: groups.k8s_master | length > 1

# 将 node 节点 kubeadm join 命令加入 fact
- set_fact:
    node_join_command: "{{ join_command_raw.stdout_lines[0] }}"

- debug:
    msg: "{{ join_command_raw.stdout_lines[0] }}"

# 将控制平面节点 kubeadm join 命令加入 fact
- set_fact:
    master_join_command: "{{ join_command_raw.stdout_lines[0] }} --control-plane --certificate-key {{ certificate_key_raw.stdout_lines[-1] }}"
  when: groups.k8s_master | length > 1

- debug:
    msg: "{{ join_command_raw.stdout_lines[0] }} --control-plane --certificate-key {{ certificate_key_raw.stdout_lines[-1] }}"
  when: groups.k8s_master | length > 1

- meta: flush_handlers