all:
  hosts:
    master:
      ansible_host: 10.1.0.100
    node1:
      ansible_host: 10.1.0.101
    node2:
      ansible_host: 10.1.0.102
    node3:
      ansible_host: 10.1.0.103
  children:
    k8s_master:
      hosts:
        master:
    k8s_node:
      hosts:
        node1:
        node2:
        node3:
