all:
  hosts:
    master:
      ansible_host: 192.168.1.100
    node1:
      ansible_host: 192.168.1.101
    node2:
      ansible_host: 192.168.1.102
  children:
    k8s_master:
      hosts:
        master:
    k8s_node:
      hosts:
        node1:
        node2:
